# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "avto-ai-app-beta"
client_id = "457efdee775d1ccfdb33b3c6f28f14fe"
application_url = "https://spare-aging-ricky-mighty.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://spare-aging-ricky-mighty.trycloudflare.com/auth/callback",
  "https://spare-aging-ricky-mighty.trycloudflare.com/auth/shopify/callback",
  "https://spare-aging-ricky-mighty.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "avtoaitest.myshopify.com"
