# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7434be098e4b8932f70487d8f0bb500e"
name = "avto-test"
application_url = "https://novelty-owners-photographs-injuries.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "avto-apparel.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://novelty-owners-photographs-injuries.trycloudflare.com/auth/callback",
  "https://novelty-owners-photographs-injuries.trycloudflare.com/auth/shopify/callback",
  "https://novelty-owners-photographs-injuries.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
