# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fece4918c1f3f02265d259c2741b5ecd"
name = "AVTO"
application_url = "https://wash-symantec-moms-analyzed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-41246cef.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://wash-symantec-moms-analyzed.trycloudflare.com/auth/callback",
  "https://wash-symantec-moms-analyzed.trycloudflare.com/auth/shopify/callback",
  "https://wash-symantec-moms-analyzed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
